"""
Integration test for IVFFlat cosine retrieval.

Uses an in-memory approach: patches the DB session so we can verify the
SQL generated by retriever.py without a real PostgreSQL instance.
"""
import pytest
from unittest.mock import AsyncMock, MagicMock


@pytest.mark.asyncio
async def test_retriever_executes_cosine_query():
    """
    Verify that retrieve_anecdotes issues SET ivfflat.probes and the
    cosine-distance ORDER BY query, and returns content strings.
    """
    fake_rows = [MagicMock(content="Led payments team."), MagicMock(content="Improved latency.")]

    mock_execute = AsyncMock()
    mock_execute.return_value.__aiter__ = AsyncMock(return_value=iter(fake_rows))
    mock_execute.return_value = fake_rows

    mock_session = AsyncMock()
    mock_session.execute = mock_execute

    from app.rag.retriever import retrieve_anecdotes

    embedding = [0.0] * 1536
    await retrieve_anecdotes(mock_session, embedding, top_k=2)

    # Should have called execute twice: SET probes + SELECT
    assert mock_execute.call_count == 2

    # First call should set probes
    first_call_sql = str(mock_execute.call_args_list[0][0][0])
    assert "probes" in first_call_sql.lower()

    # Second call should contain cosine operator
    second_call_sql = str(mock_execute.call_args_list[1][0][0])
    assert "<=>" in second_call_sql


@pytest.mark.asyncio
async def test_retriever_respects_top_k():
    """top_k parameter should flow through to the LIMIT clause."""
    mock_session = AsyncMock()
    mock_session.execute.return_value = []

    from app.rag.retriever import retrieve_anecdotes

    await retrieve_anecdotes(mock_session, [0.1] * 1536, top_k=7)

    # The second execute call should bind k=7
    second_call = mock_session.execute.call_args_list[1]
    bound_params = second_call[0][1]
    assert bound_params["k"] == 7
